import { ApiPropertyOptional } from '@nestjs/swagger';
import { IsInt, IsNumber, IsObject, IsOptional, IsString, Length, Min } from 'class-validator';

export class CreateVariantDto {
  @ApiPropertyOptional({ example: 'IPH-16P-BLK-256', description: 'If omitted, auto-generated by the server.' })
  @IsOptional()
  @IsString()
  @Length(1, 100)
  sku?: string;

  @ApiPropertyOptional({ example: 59900000 })
  @IsNumber()
  @Min(0)
  price: number;

  @ApiPropertyOptional({ example: 10, default: 0 })
  @IsOptional()
  @IsInt()
  @Min(0)
  stock?: number;

  @ApiPropertyOptional({
    example: { color: 'black', storage: '256GB' },
    description: 'Each key/value must exist in AttributeOption table.',
  })
  @IsOptional()
  @IsObject()
  attributes?: Record<string, string>;
}
